QT.printsupport_private.VERSION = 5.12.5
QT.printsupport_private.name = QtPrintSupport
QT.printsupport_private.module =
QT.printsupport_private.libs = $$QT_MODULE_LIB_BASE
QT.printsupport_private.includes = $$QT_MODULE_INCLUDE_BASE/QtPrintSupport/5.12.5 $$QT_MODULE_INCLUDE_BASE/QtPrintSupport/5.12.5/QtPrintSupport
QT.printsupport_private.frameworks =
QT.printsupport_private.depends = core_private gui_private widgets_private printsupport
QT.printsupport_private.uses =
QT.printsupport_private.module_config = v2 internal_module
QT.printsupport_private.enabled_features = cups cupsjobwidget
QT.printsupport_private.disabled_features =
QMAKE_LIBS_CUPS = /home/jovyan/CSCI4118/assignment-2-python-refresher-juba2320/src/workflow/snakemake/.snakemake/conda/396349174c567cb60ab62534de17aa49_/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libcups.so
