name: Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  run_style_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: swe4s
      - run: |
          cd src
          pycodestyle $(git ls-files "*.py")
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd tests/unit_tests
          python -m unittest test_my_utils.py
  run_functional_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd tests/functional_tests
          bash test_print_fires.sh 
