name: Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  run_style_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd src
          pycodestyle my_utils.py
          pycodestyle print_fires.py
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd tests/unit_tests
          python -m unittest test_my_utils.py
  run_functional_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd tests/functional_tests
          bash test_print_fires.sh 
